import type { NextPage } from "next";
import Head from "next/head";
import { Nav } from "../components/nav/Nav";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Edu Platform</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Nav />
      </header>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4"></main>
    </>
  );
};

export default Home;
