import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Nav } from "../components/nav/Nav";

const Home: NextPage = () => {
  const { status } = useSession();
  const router = useRouter();

  if (status === "unauthenticated") {
    router.push("/login");
    return null;
  }

  return (
    <>
      <Head>
        <title>Edu Platform</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Nav />
      </header>

      <main
        data-testid="main"
        className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4"
      ></main>
    </>
  );
};

export default Home;
